spring:
  devtools:
    livereload:
      enabled: true
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8001
          predicates:
            - Path=/user/**
        - id: board-service
          uri: http://localhost:8002
          predicates:
            - Path=/board/**

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway: DEBUG

jwt:
  secret: 64KY64qU7LWc6rec64+Z7J206rOg7J206rG07JWU7Zi47J206rOgIUDsnbTqsbTrrZDrg5A/JQ==
  acess-expiredTime: 3600 # 1시간